export const E2E_SW_METHODS = {
  E2E_MOCK_ROUTE: 'E2E_MOCK_ROUTE',
  E2E_MOCK_ROUTE_ONCE: 'E2E_MOCK_ROUTE_ONCE',
  E2E_MOCK_CLEAR: 'E2E_MOCK_CLEAR',
  E2E_CLIENT_RESUME: 'E2E_CLIENT_RESUME',
};

export const DIRECTION = {
  CLIENT: 'e2e-sw-client',
  HOST: 'e2e-sw-host',
};
